# Site
name: "quietly"
title: "writing about just about everything"
description: "This is mainly meant to be a personal blog and will encompass just about anything and everything with the possible exception of sporting events. If you're here looking for sporting events, may I suggest visiting ESPN instead?"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
# google_analytics: 'UA-xxxxxxxx-1'
# disqus: 'demowebsite'
# mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
# email: ''

# Authors
authors:
  hrisc:
    name: Hrishit Chaudhuri
    display_name: hrishitchaudhuri
    # gravatar: 
    # e mail: 34icecreamsandwich@gmail.com
    # web: 
    # twitter: 
    # description: ""
    
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
